### ISSUE TITLE
Small bugs that affect the interface and need to redo your config.

### ISSUE THREAD

**Issue by Shaztech** [Lenochxd/WebDeck#20]
-When you add an icon and you remove the "Button Title" and hit save. The page won't reload anymore and your stuck on an error page, even if you restart WebDeck.

-If your remove the button FullScreen the interface become super small and all buttons are on one line. (You can move the button into a folder without a problem, but removing it cause issue.)

All test are gave the same results on Chrome/Chromium browsers

Also it would be nice to have info on the "Execute batch code" I've tried to enter a command (.exe) with path and parameters. It's not working. I've tried with the path in quotes, without quotes...

Thanks

**Comment by Lenochxd** [comment]
Fixed on [1.8.6](https://github.com/Lenochxd/WebDeck/releases/tag/v1.8.6) (6d2072a690ed6088638f6ffee48a23776fac0904 & 89dc655a00e71ca4835dbbc0e0eec6518a16f17b)
