### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by GamerClassN7** [Lenochxd/WebDeck#24]
**Is your feature request related to a problem? Please describe.**
I was not able to get application running correctly tray icon is present but after scaning QR there is just black screen and local config shotcut also dont work.

**Describe the solution you'd like**
Simple log file with some dubug informations would be nice :)

**Comment by Lenochxd** [comment]
The issue has been resolved with commits c2b325b, b2a91e9, and 32dc1bf. The fix will be included in the next release. Thank you for your patience!
