### ISSUE TITLE
German language file

### ISSUE THREAD

**Issue by Dtrieb** [Lenochxd/WebDeck#31]
Here is my Version of the german language:
[de_DE.lang.txt](https://github.com/user-attachments/files/16782382/de_DE.lang.txt)

**Comment by Lenochxd** [comment]
Thanks for the file! Could you please create a pull request (PR) with it? If you need help, I can assist, or you can check the [GitHub PR guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).

**Comment by Lenochxd** [comment]
I’ve merged the German translation into the project. Since I didn’t get a PR from you, I created a commit with your name and credited you as the author.

This will be included in the upcoming release. Thanks again for your contribution! :)

**Comment by Dtrieb** [comment]
Yes sorry I didn't get it by my own. 😔
