### ISSUE TITLE
Crash on first site attempt

### ISSUE THREAD

**Issue by charely6** [Lenochxd/WebDeck#7]
So I downloaded and started the program but when I first tried to connect with my phone I got a can't connect and this error popped up on my computer. 

![image](https://github.com/Lenochxd/WebDeck/assets/14881845/4e9d0343-e63d-49a0-8deb-5167b5462465)

**Comment by Lenochxd** [comment]
Thanks for letting me know, this will be fixed in the next update. What GPU do you have?

**Comment by charely6** [comment]
NVIDIA GeForce GT 640
yeah I think its an older one.

**Comment by Lenochxd** [comment]
Also, you said "crash on **first** attempts, does that mean the error only happened once?

**Comment by charely6** [comment]
if I quit it and started it again it I got the error, but I couldn't see anything in the browser interface.

**Comment by Lenochxd** [comment]
Seems normal to me! If you want to disable the error, you can set the `GPU usage method` setting to `None` in the browser interface.

**Comment by charely6** [comment]
well the issues is when I tri to open the config or the site on another device it doesn't work
I just get a refused to connect message

**Comment by Lenochxd** [comment]
By default, if it crashes on startup it's set to AMD, but your GPU is an outdated Nvidia, so it doesn't crash on startup but crashes later.

Will be fixed! Thanks 🙏

**Comment by Lenochxd** [comment]
Fixed on [1.7.3](https://github.com/Lenochxd/WebDeck/releases/tag/v1.7.3) ([6db6e79](https://github.com/Lenochxd/WebDeck/commit/6db6e7966123809f7062de23d285cb9c3401fe2e))
