### ISSUE TITLE
App not starting.

### ISSUE THREAD

**Issue by Zero1338** [Lenochxd/WebDeck#9]
I downloaded and installed webdeck and have the app on my start page. When I click to start it I get a window that asks do I want an app from an unknown publisher to make changes on your PC I click Yes but nothing starts.

**Comment by Zero1338** [comment]
Yup, got it. Thank you!

**Comment by Lenochxd** [comment]
UX issue fixed in d8774cd296a96a7a426339af7c49e0b8abe81094
